In [1]:
%cd ../..

/home/shpotes/Courses/EAFIT/inteligencia-artificial/santiago/clustering/clustering


In [2]:
from functools import partial
import jax
import jax.numpy as jnpt
import numpy as onp
from src import KMeans, KMeansPlusPlus

In [3]:
X1 = onp.random.normal([1, 10], 0.05, size=(2, 2))
y1 = onp.zeros(2)
X2 = onp.random.normal([3, 5], 0.01, size=(3, 2))
y2 = onp.ones(3)

x = onp.vstack([X1, X2])
y = onp.concatenate([y1, y2])

idxs = onp.arange(5)
onp.random.shuffle(idxs)
x = x[idxs]
y = y[idxs]

In [8]:
KMeans(n_clusters=2).fit_predict(x)

DeviceArray([1, 0, 1, 0, 0], dtype=int32)

In [11]:
KMeansPlusPlus(n_clusters=2).fit_predict(x)

DeviceArray([1, 0, 1, 0, 0], dtype=int32)

In [9]:
y

array([0., 1., 0., 1., 1.])